apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: client-service
spec:
  hosts:
    - client-service
  http:
    - route:
        - destination:
            host: client-service
            subset: blue
          weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: client-service
spec:
  host: client-service
  subsets:
    - name: blue
      labels:
        version: v1
    - name: green
      labels:
        version: v2
