apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: client-service
spec:
  hosts:
    - client-service
  http:
    - route:
        - destination:
            host: client-service
            subset: stable
          weight: 90
        - destination:
            host: client-service
            subset: canary
          weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: client-service
spec:
  host: client-service
  subsets:
    - name: stable
      labels:
        version: v1
    - name: canary
      labels:
        version: v2
