apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
  namespace: garage-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service # This must match the labels below
  template:
    metadata:
      labels:
        app: client-service # Ensure this matches the selector
    spec:
      containers:
        - name: client-service
          image: garage-management-client_service:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: garage-management
spec:
  selector:
    app: client-service # This must match the pod template labels
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
