apiVersion: apps/v1
kind: Deployment
metadata:
  name: planification-service
  namespace: garage-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planification-service
  template:
    metadata:
      labels:
        app: planification-service
    spec:
      containers:
        - name: planification-service
          image: garage-management-planification_service:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: planification-service
  namespace: garage-management
spec:
  selector:
    app: planification-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
